# Generated by Django 4.2.23 on 2025-07-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Bids'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('target_roas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_cpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_ctr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('campaign_start', models.DateField()),
                ('campaign_end', models.DateField()),
                ('bidding_deadline', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_campaigns', to=settings.AUTH_USER_MODEL)),
                ('selected_agency_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('META', 'Meta (Facebook & Instagram)'), ('TIKTOK', 'TikTok'), ('GOOGLE', 'Google Ads'), ('LINKEDIN', 'LinkedIn')], max_length=20)),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'platform', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CampaignBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guaranteed_roas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('guaranteed_cpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guaranteed_ctr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proposal_text', models.TextField()),
                ('estimated_timeline', models.CharField(max_length=100)),
                ('bonus_structure', models.JSONField(default=dict)),
                ('is_selected', models.BooleanField(default=False)),
                ('competitiveness_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='campaigns.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'agency_user')},
            },
        ),
    ]
